spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 199811
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8082